### Get all notes
GET http://localhost:8080/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ1c2VybmFtZSI6InVzZXIiLCJuYW1lIjoidXNlcnRlc3QiLCJub3RlcyI6W10sImlkIjoiNjQ1NTk1MGI2MzFkZmY1ZTMxNDE1NGMzIn0sImlhdCI6MTY4MzQxMDE5MywiZXhwIjoxNjg2MDAyMTkzfQ.aXO7pQ33MJY2vdU4XjbLBOV52JoKmsGXUKh-3h4veSE

### Get a single note
GET http://localhost:8080/api/notes/6456cd9db924c293299c92b4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ1c2VybmFtZSI6InVzZXIiLCJuYW1lIjoidXNlcnRlc3QiLCJub3RlcyI6W10sImlkIjoiNjQ1NTk1MGI2MzFkZmY1ZTMxNDE1NGMzIn0sImlhdCI6MTY4MzQxMDE5MywiZXhwIjoxNjg2MDAyMTkzfQ.aXO7pQ33MJY2vdU4XjbLBOV52JoKmsGXUKh-3h4veSE

### Create a note
POST http://localhost:8080/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ1c2VybmFtZSI6InVzZXIiLCJuYW1lIjoidXNlcnRlc3QiLCJub3RlcyI6W10sImlkIjoiNjQ1NTk1MGI2MzFkZmY1ZTMxNDE1NGMzIn0sImlhdCI6MTY4MzQxMDE5MywiZXhwIjoxNjg2MDAyMTkzfQ.aXO7pQ33MJY2vdU4XjbLBOV52JoKmsGXUKh-3h4veSE

{
    "content": "New note 2",
    "important": true
}

### Delete a note
DELETE http://localhost:8080/api/notes/6456cd9db924c293299c92b4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ1c2VybmFtZSI6InVzZXIiLCJuYW1lIjoidXNlcnRlc3QiLCJub3RlcyI6W10sImlkIjoiNjQ1NTk1MGI2MzFkZmY1ZTMxNDE1NGMzIn0sImlhdCI6MTY4MzQxMDE5MywiZXhwIjoxNjg2MDAyMTkzfQ.aXO7pQ33MJY2vdU4XjbLBOV52JoKmsGXUKh-3h4veSE

### Update a note
PUT http://localhost:8080/api/notes/6456cd9db924c293299c92b4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ1c2VybmFtZSI6InVzZXIiLCJuYW1lIjoidXNlcnRlc3QiLCJub3RlcyI6W10sImlkIjoiNjQ1NTk1MGI2MzFkZmY1ZTMxNDE1NGMzIn0sImlhdCI6MTY4MzQxMDE5MywiZXhwIjoxNjg2MDAyMTkzfQ.aXO7pQ33MJY2vdU4XjbLBOV52JoKmsGXUKh-3h4veSE

{
    "content": "Updated note",
    "important": true
}
